In [1]:
Q = [[1,2],[3,4],[5,6]]

In [3]:
for i,element in enumerate(Q):
    print(i)
    print(i)

0
0
1
1
2
2


In [9]:
import numpy as np
R = np.arange(-4,4+1e-9,0.1)
X,Y = np.meshgrid(R,R)
print(X.shape)


(81, 81)


In [12]:
x = np.array([1,2])

In [13]:
x

array([1, 2])

In [15]:
R = np.arange(1,4)

In [16]:
X,Y = np.meshgrid(R,R)

In [17]:
print(X)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [18]:
Z = np.array([X,Y])

In [19]:
print(Z)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 1 1]
  [2 2 2]
  [3 3 3]]]


In [20]:
Z = X,Y

In [24]:
x1 = np.random.randint(10, size=6)  # random one-dimensional integer array
x2 = np.random.randint(10, size=(5, 4))  

In [27]:
print(x2)
print(x1.shape)
print(x2.shape)

[[9 0 7 4]
 [4 4 7 6]
 [5 6 9 0]
 [9 1 4 4]
 [8 7 6 0]]
(6,)
(5, 4)


In [28]:
print(x1)

[0 4 7 2 3 1]
